### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by 98wh** [hongluzhou/hierarchical_information_diffusion#2]
Can you tell me where the original twitter data can be downloaded? And I also would like to know which Memes dataset you used, the Raw phrases data or Phrase cluster data? thanks~

**Comment by hongluzhou** [comment]
Thanks for the injury! Please consider using the following script to download the related raw datasets:

**Twitter:**
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-06.txt.gz
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-07.txt.gz
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-08.txt.gz
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-09.txt.gz
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-10.txt.gz
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-11.txt.gz
wget https://snap.stanford.edu/data/bigdata/twitter7/tweets2009-12.txt.gz

Twitter social graph (who-follows-whom graph):
wget http://an.kaist.ac.kr/~haewoon/release/twitter_social_graph/twitter_rv.tar.gz
wget http://an.kaist.ac.kr/~haewoon/release/numeric2screen.tar.gz

Ref:
http://an.kaist.ac.kr/traces/WWW2010.html
https://snap.stanford.edu/data/twitter7.html


**Memetracker:**
wget http://snap.stanford.edu/memetracker/srcdata/clust-qt08080902w3mfq5.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2008-08.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2008-09.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2008-10.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2008-11.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2008-12.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2009-01.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2009-02.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2009-03.txt.gz
wget https://snap.stanford.edu/data/bigdata/memetracker9/quotes_2009-04.txt.gz

For the Memetracker dataset, we use the [phrase cluster data](https://snap.stanford.edu/data/other.html).

**Comment by 98wh** [comment]
Thanks♪(･ω･)ﾉ
