### ISSUE TITLE
 The dataset is no longer valid

### ISSUE THREAD

**Issue by cyber-loafing** [hongluzhou/hierarchical_information_diffusion#4]
The Google Drive link to the dataset is no longer valid. Could you provide a new link?

**Comment by hongluzhou** [comment]
Truly unfortunate that I wasn't able to find a copy of the processed data. However, the following link seems to have the raw data:
https://drive.google.com/drive/folders/17OGUjzGp5ls12okvsVLAzdwiSWqkoiWD?usp=sharing
Perhaps you can follow the instructions on data/README.md to process it: https://github.com/hongluzhou/HID/blob/master/data/README.md#data

**Comment by cyber-loafing** [comment]
thanks for you quick response
